version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    ECR_REPO: "779846795398.dkr.ecr.us-east-1.amazonaws.com/game-2048"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
<<<<<<< HEAD
      - echo "Region: $AWS_REGION"
      - echo "Repo: $ECR_REPO"
=======
      - echo "$AWS_REGION"
      - echo "$ECR_REPO"
>>>>>>> 020b34e52056bd995316001f6f95805c8e66fd8d
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO

  build:
    commands:
      - echo Building Docker image...
<<<<<<< HEAD
      - pwd
      - ls -la
      - cd project-1/2048
      - pwd
      - ls -la
=======
      - ls -la
      - cd project-1/2048
>>>>>>> 020b34e52056bd995316001f6f95805c8e66fd8d
      - docker build -t game-2048 .
      - docker tag game-2048:latest $ECR_REPO:latest

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $ECR_REPO:latest
      - echo Build completed on `date`
